tz: "America/Sao_Paulo" # Timezone

# Virtual machine development user.
user: "nginx"
password: "chucknorris"

# The project details
project: "PROJECT_NAME"
requirements_path: "requirements.txt"

# Used in nginx and uwsgi
domain_name: "project_name.com.br"

# MySQL database details and credentials
db_name: "project_name"
db_user: "project_name"
db_password: "chucknorris"
